name: Build and Preview Vite SolidJS App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v3 
        with:
            version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build app
        run: pnpm run build

      - name: Start server
        run: |
          serve dist --port ${{ secrets.PORT || 5000 }}
